# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

sphinx:
  configuration: docs/conf.py

formats: all

build:
  image: latest

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - sphinx
